/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/sessions/{session}/timestamps/{type}/{id}/annotations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Annotation
         * @description A free-text `note` on one timestamp. `{type}` is
         *     `communication_event` | `game_event` | `dead_air`; `{id}` is the row id
         *     within that kind. Authored by the caller: a coach while the session is
         *     `timeline_ready` or `analysis_ready`, a player only once `analysis_ready`.
         */
        post: operations["annotation.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/annotations/{annotation}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Edit Annotation
         * @description The author edits their own note or reply. A system annotation is
         *     immutable.
         */
        put: operations["annotation.update"];
        post?: never;
        /**
         * Delete Annotation
         * @description The author deletes their own note or reply; a top-level note takes its
         *     replies with it. A system annotation is immutable.
         */
        delete: operations["annotation.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/annotations/{annotation}/replies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reply to Annotation
         * @description One level only: the parent must be a top-level annotation. Coaches reply
         *     while under review or analysis-ready; players only once analysis-ready.
         */
        post: operations["annotation.reply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate a user with email and password, then issue an API token.
         */
        post: operations["auth.login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Register an account, assign its role, and create or join a team when required.
         */
        post: operations["auth.register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke the API token used for the current request. Also leaves any
         *     non-terminal session the user is still an active participant in,
         *     cancelling that session if that leaves it with no participants at all,
         *     and marks the user offline. Wrapped in a transaction so a failure
         *     partway through never leaves this state changed without the token
         *     actually being revoked.
         */
        post: operations["auth.logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/header": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard Header
         * @description The team identity block, a Communication KPI over the N most recent
         *     analysis-ready sessions, and the same window's communication-mix counts.
         *     Any active member: every member sees the same team-wide numbers, only
         *     `identity.user` differs.
         */
        get: operations["dashboard.header"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard Players
         * @description A per-player communication breakdown over the N most recent
         *     analysis-ready sessions. A coach sees every active non-coach member; a
         *     player sees only their own line plus the team median.
         */
        get: operations["dashboard.players"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{team}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Session List
         * @description Return the team's current non-terminal (queuing or in_progress) session,
         *     if any, as `live_session`, and every other session as a paginated,
         *     searchable, date-ordered `past_sessions` list. Never loads participants.
         *     Restricted to any active member of the team.
         */
        get: operations["session.index"];
        put?: never;
        /**
         * Create Session
         * @description Create a Session for the given team and add the creating Coach as its
         *     first Session Participant. Restricted to any active Coach, main or
         *     assistant. Rejected if the team already has a non-terminal
         *     (queuing/in_progress) session. The Timeline is created later, when the
         *     session is completed and enters processing.
         */
        post: operations["session.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Session Return
         * @description Return a session and its participants. Restricted to any active member
         *     of the session's team. Refused with 409 while the session is processing:
         *     the analysis pipeline is mid-run and there is no coherent session view to
         *     return yet. Progress is on the team session index instead.
         */
        get: operations["session.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/captions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Session Captions
         * @description Return one caption track per player who recorded audio: the transcript's
         *     status and, when it completed, its sentences with nested words and
         *     millisecond spans. A `failed` or empty transcript still yields a track
         *     with its status and no sentences. Restricted to any active member of the
         *     session's team. Refused with 409 while the session is processing, served
         *     from timeline_ready onward.
         */
        get: operations["session.captions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Session Timeline
         * @description Return the session, its Timeline, and one entry per participant who
         *     recorded, each carrying that player's own communication-event timestamps
         *     (with callouts) ordered by start, plus their transcript / AOD / VOD
         *     metadata. Recording metadata only, no URLs. Restricted to any active
         *     member of the session's team. Refused with 409 while the session is
         *     processing, served from timeline_ready onward.
         */
        get: operations["session.timeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/timeline-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Session Timeline Summary
         * @description Return communication frequency, event counts by type (informative /
         *     declarative / compound / redundant) and provisional team-aggregate
         *     silence metrics, at team and per-player level. Restricted to any active
         *     member of the session's team. Refused with 409 while the session is
         *     processing, served from timeline_ready onward.
         */
        get: operations["session.timelineSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transition Session
         * @description A coach-driven state move that carries no payload. `to` names the move:
         *
         *     - `cancelled` — abort the session (from `queuing` or `in_progress`).
         *     - `reanalyze` — rebuild the timeline from the stored recordings using the
         *       team's current settings; returns 202 and re-opens at `timeline_ready`
         *       once detection finishes. Discards all timeline-management work.
         *     - `analysis_ready` — open the reviewed timeline to players (from
         *       `timeline_ready`, once every timestamp is reviewed).
         *     - `timeline_ready` — reopen review (from `analysis_ready`).
         *
         *     `start` and `complete` are their own endpoints. Any active Coach; whether
         *     the move is legal from the session's current status is the model's guard,
         *     surfaced as 422. See docs/adr/0010-timeline-management.md.
         */
        post: operations["session.transition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Join Session
         * @description Add the authenticated active team member as a Session Participant while
         *     the session is queuing, snapshotting their current team role. Idempotent:
         *     joining again is a no-op success, not an error. A member who'd
         *     previously left is reactivated rather than staying stuck as departed.
         */
        post: operations["session.join"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/consent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Consent
         * @description Move the authenticated caller's own participant row from needs_consent
         *     to ready. Idempotent once already ready. Restricted to any active member
         *     of the session's team; a Coach, a non-participant, or a session past the
         *     point of consent is rejected with 422.
         */
        post: operations["session.consent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Session
         * @description Transition a queuing session to in_progress. Restricted to any active
         *     Coach on the session's team, not just its creator.
         */
        post: operations["session.start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Session
         * @description Take an audio and video slot for every recording player, store whatever
         *     files the slots hold, then transition the in_progress session to completed
         *     and sweep every recording participant to completed. Restricted to any
         *     active Coach on the session's team, not just its creator. Rejected with
         *     422 if the session is not in_progress, the submitted player ids do not
         *     match the recording roster exactly, or no slot holds both files.
         */
        post: operations["session.complete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request to Join (OPTIONAL FOR MVP)
         * @description Submit a join request for a team by its team code. The request stays pending
         *     until the main coach of that team approves or rejects it. A user
         *     may only have one active membership or pending request at a time.
         */
        post: operations["team.join"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Team Return
         * @description Return a team, including its active members, only when the authenticated
         *     user is an active member of that team.
         */
        get: operations["team.show"];
        /**
         * Update Team (OPTIONAL FOR MVP)
         * @description Allow only the active main coach to update a team's name or description.
         *     Team codes are generated at creation and cannot be changed.
         */
        put: operations["team.update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/members/{user}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Member (OPTIONAL FOR MVP)
         * @description Remove an active player or assistant coach from the team, returning them to
         *     a teamless state. The main coach cannot be removed this way; see leave().
         *     Restricted to the team's main coach.
         */
        delete: operations["team.removeMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Leave Team (OPTIONAL FOR MVP)
         * @description Leave the authenticated user's active team. If the leaving member is the
         *     main coach, the entire team is disbanded: every active member,
         *     including the leader, is returned to a teamless state.
         */
        post: operations["team.leave"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/join-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Join Requests Return (OPTIONAL FOR MVP)
         * @description Return the pending join requests for a team. Restricted to the team's main
         *     coach.
         */
        get: operations["team.joinRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/join-requests/{user}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Decide Join Request (OPTIONAL FOR MVP)
         * @description Approve or reject a pending join request. Approving a player request is
         *     rejected once the team already has 5 active players. Restricted to the
         *     team's main coach.
         */
        put: operations["team.decideJoinRequest"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Team Settings Return
         * @description Return the active team's detection settings (dead-air threshold,
         *     communication-event padding, game-alignment window, keyword lists).
         *     Restricted to any active Coach, main or assistant.
         */
        get: operations["teamSettings.show"];
        /**
         * Update Team Settings
         * @description Update the active team's dead-air threshold, and its communication-event
         *     padding and game-alignment window when those fields are supplied.
         *     Restricted to any active Coach, main or assistant.
         */
        put: operations["teamSettings.update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/settings/keywords": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Team Keywords
         * @description Replace the active team's detection keyword list. The request carries the
         *     complete desired list per category; the server reconciles it against
         *     what's stored, inserting new words and deleting dropped ones. Restricted
         *     to any active Coach, main or assistant.
         */
        put: operations["teamSettings.updateKeywords"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/timestamps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Timestamp
         * @description A coach adds a communication event (to one participant) or a dead-air
         *     period the detector missed. Game events are feed-only. The new row starts
         *     reviewed, stamped to its author.
         */
        post: operations["timestamp.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/timestamps/review-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark Every Timestamp Reviewed
         * @description Stamp every currently-unreviewed timestamp in the session to the acting
         *     Coach. Idempotent.
         */
        post: operations["timestamp.reviewAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/timestamps/{type}/{id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Timestamp Review
         * @description `{ "reviewed": true }` signs the timestamp off (stamped to the acting
         *     Coach); `{ "reviewed": false }` clears the sign-off. Returns the session's
         *     running `{ reviewed, total }`.
         */
        put: operations["timestamp.review"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/timestamps/{type}/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Edit Timestamp
         * @description Partial update against a per-kind whitelist. Any change clears the row's
         *     review stamp.
         */
        put: operations["timestamp.update"];
        post?: never;
        /**
         * Delete Timestamp
         * @description Removes the row and its whole annotation subtree (system rows, coach
         *     notes, replies). A game event carries no annotations.
         */
        delete: operations["timestamp.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Profile Return
         * @description Return the authenticated user's profile, roles, and active team memberships.
         */
        get: operations["user.show_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Profile Return
         * @description Return the authenticated user's profile, roles, and active team memberships.
         */
        get: operations["user.show_4"];
        /**
         * Update Profile
         * @description Update the authenticated user's permitted profile fields without allowing role changes.
         */
        put: operations["user.update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Password
         * @description Change the authenticated user's password after verifying their current password.
         */
        put: operations["user.updatePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Active Teams Return
         * @description Return only the teams in which the authenticated user is currently an active member.
         */
        get: operations["user.teams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CalloutDetectionResource */
        CalloutDetectionResource: {
            keyword: string;
            normalized_keyword: string;
            category: string;
            start_ms: number;
            end_ms: number;
            confidence: number;
        };
        /** CaptionSentenceResource */
        CaptionSentenceResource: {
            position: number;
            text: string;
            start_ms: number;
            end_ms: number;
            confidence: number;
            words?: components["schemas"]["CaptionWordResource"][];
        };
        /** CaptionTrackResource */
        CaptionTrackResource: {
            participant_id: number;
            user_id: number;
            username?: string;
            status: string;
            language_code: string | null;
            confidence: number | null;
            audio_duration_ms: number | null;
            sentences: components["schemas"]["CaptionSentenceResource"][];
        };
        /** CaptionWordResource */
        CaptionWordResource: {
            position: number | null;
            text: string;
            start_ms: number;
            end_ms: number;
            confidence: number;
        };
        /** CompleteSessionRequest */
        CompleteSessionRequest: {
            players: {
                user_id: number;
                /**
                 * Format: binary
                 * @description Maximum file size: 204800 kilobytes.
                 */
                audio?: string | null;
                /**
                 * Format: binary
                 * @description Maximum file size: 2097152 kilobytes.
                 */
                video?: string | null;
            }[];
            game_events?: {
                /** @enum {string} */
                type: "kill" | "death" | "spike_plant" | "spike_defuse" | "round_win" | "round_lost";
                /** @enum {string} */
                side?: "ally" | "enemy";
                match_time_ms: number;
                round_number?: number | null;
                note?: string | null;
            }[] | null;
        };
        /** DecideJoinRequest */
        DecideJoinRequest: {
            /** @enum {string} */
            action: "approve" | "reject";
        };
        /** JoinTeamRequest */
        JoinTeamRequest: {
            team_code: string;
        };
        /** RecordingMetaResource */
        RecordingMetaResource: {
            id: number;
            original_filename: string;
            mime_type: string;
            size_bytes: number;
        };
        /** RegisterRequest */
        RegisterRequest: {
            username: string;
            /** Format: email */
            email: string;
            password: string;
            /** @enum {string} */
            role: "Coach" | "Player";
            riot_id?: string | null;
            /**
             * @description Team involvement is entirely optional at registration: omit both team_action and
             *     team_code to register without a team and join one later.
             * @enum {string|null}
             */
            team_action?: "create" | null;
            team_name?: string | null;
            description?: string | null;
            team_code?: string | null;
            password_confirmation: string;
        };
        /** SessionCaptionsResource */
        SessionCaptionsResource: {
            session_id: number;
            tracks: components["schemas"]["CaptionTrackResource"][];
        };
        /** SessionParticipantResource */
        SessionParticipantResource: {
            user_id: number;
            username?: string;
            participant_role: string;
            participant_status: string;
            /** Format: date-time */
            joined_at: string | null;
            /** Format: date-time */
            left_at: string | null;
        };
        /** SessionResource */
        SessionResource: {
            id: number;
            team_id: number;
            created_by: number;
            session_code: string | null;
            session_name: string;
            status: string;
            /** Format: date-time */
            created_at: string | null;
            participants?: components["schemas"]["SessionParticipantResource"][];
            /**
             * @description Only a processing session runs the aggregate query; every other
             *     state omits the key entirely.
             */
            transcription?: {
                total: number;
                completed: number;
                failed: number;
            };
        };
        /** SessionTimelineResource */
        SessionTimelineResource: {
            session_id: number;
            status: string;
            timeline: {
                id: number;
                /** Format: date-time */
                created_at: string | null;
                duration_ms: null;
            };
            /**
             * @description The session-wide spine the per-participant callouts are read
             *     against: point-in-time game events and interval dead-air periods
             *     merged, ordered by start_ms. Sits ahead of participants.
             */
            game_events: unknown[];
            participants: components["schemas"]["TimelineParticipantResource"][];
        };
        /** SessionTimelineSummaryResource */
        SessionTimelineSummaryResource: {
            session_id: number;
            /**
             * @description The analysis window: the longest recording in the session
             *     (max transcript audio_duration_ms), which under the zero-offset
             *     assumption bounds the whole timeline. Denominator for the
             *     frequency and *_percentage figures.
             */
            session_window_ms: number;
            team: {
                frequency_per_min: number;
                comm_event_count: {
                    informative: number;
                    declarative: number;
                    compound: number;
                    total: number;
                };
                redundant_count: number;
                game_events: {
                    total: number;
                    by_type: string;
                };
                alignment: {
                    possibly_positive: number;
                    possibly_negative: number;
                    neutral: number;
                    assessed_total: number;
                };
                dead_air: {
                    count: string;
                    longest_ms: number;
                };
                /**
                 * @description Percentages of the session window, via TimelineMetrics::percentageOfWindow:
                 *     talk_percentage            = total_talk_ms     / session_window, as a percent
                 *     silence_percentage         = total_silence_ms  / session_window, as a percent
                 *     longest_silence_percentage = longest_silence_ms / session_window, as a percent
                 *     talk and silence are rounded independently, so they only sum to ~100.
                 */
                talk_percentage: number;
                silence_percentage: number;
                longest_silence_percentage: number;
                review: {
                    reviewed: string;
                    total: number;
                    complete: boolean;
                };
            };
            participants: components["schemas"]["TimelineSummaryParticipantResource"][];
        };
        /** StoreSessionRequest */
        StoreSessionRequest: {
            session_name: string;
        };
        /** TeamMemberResource */
        TeamMemberResource: {
            id: number;
            username: string;
            user_code: string;
            is_online: boolean;
            member_role: string;
            status: string;
            joined_at: string;
        };
        /** TeamResource */
        TeamResource: {
            id: number;
            team_code: string;
            team_name: string;
            description: string | null;
            /** Format: date-time */
            disbanded_at: string | null;
            /** Format: date-time */
            created_at: string | null;
            members?: components["schemas"]["TeamMemberResource"][];
        };
        /** TeamSettingsResource */
        TeamSettingsResource: {
            team_id: string;
            dead_air_threshold_ms: string;
            comm_event_padding_ms: string;
            game_alignment_window_ms: string;
            informative_keywords: string;
            declarative_keywords: string;
            /**
             * @description Newest touch across all three setting rows: a keyword-list edit
             *     touches its bucket row, so it moves this too, not just a
             *     dead-air-threshold change.
             */
            updated_at: unknown;
        };
        /** TimelineParticipantResource */
        TimelineParticipantResource: {
            participant_id: number;
            user_id: number;
            username?: string;
            transcript: components["schemas"]["TranscriptSummaryResource"] | null;
            aod: components["schemas"]["RecordingMetaResource"];
            vod: components["schemas"]["RecordingMetaResource"] | null;
            timestamps: components["schemas"]["TimelineTimestampResource"][];
        };
        /** TimelineSummaryParticipantResource */
        TimelineSummaryParticipantResource: {
            participant_id: number;
            user_id: number;
            username?: string;
            frequency_per_min: number;
            comm_event_count: {
                informative: number;
                declarative: number;
                compound: number;
                total: number;
            };
            redundant_count: number;
            alignment: {
                possibly_positive: number;
                possibly_negative: number;
                neutral: number;
                assessed_total: number;
            };
            review: {
                reviewed: number;
                total: number;
            };
        };
        /** TimelineTimestampResource */
        TimelineTimestampResource: {
            /** @constant */
            type: "communication_event";
            id: number;
            communication_type: string;
            is_redundant: boolean;
            start_ms: number;
            end_ms: number;
            content: string;
            reviewed: boolean;
            /** Format: date-time */
            reviewed_at: string | null;
            reviewed_by: number | null;
            created_by: number | null;
            callouts?: components["schemas"]["CalloutDetectionResource"][];
            annotations: {
                [key: string]: unknown;
            }[];
        };
        /** TranscriptSummaryResource */
        TranscriptSummaryResource: {
            id: number;
            status: string;
            language_code: string | null;
            confidence: number | null;
            audio_duration_ms: number | null;
        };
        /** UpdatePasswordRequest */
        UpdatePasswordRequest: {
            current_password: string;
            password: string;
            password_confirmation: string;
        };
        /** UpdateProfileRequest */
        UpdateProfileRequest: {
            username?: string;
            /** Format: email */
            email?: string;
            riot_id?: string | null;
            role?: string;
            member_role?: string;
        };
        /** UpdateTeamKeywordsRequest */
        UpdateTeamKeywordsRequest: {
            informative_keywords: string[];
            declarative_keywords: string[];
        };
        /** UpdateTeamRequest */
        UpdateTeamRequest: {
            team_name?: string;
            description?: string | null;
            team_code?: string;
        };
        /** UpdateTeamSettingsRequest */
        UpdateTeamSettingsRequest: {
            dead_air_threshold_ms: number;
            comm_event_padding_ms?: number;
            game_alignment_window_ms?: number;
        };
        /** UserResource */
        UserResource: {
            id: number;
            username: string;
            email: string;
            user_code: string;
            riot_id: string | null;
            is_online: boolean;
            roles?: string[];
            teams?: components["schemas"]["TeamResource"][];
            /** Format: date-time */
            created_at: string | null;
        };
    };
    responses: {
        /** @description Validation error */
        ValidationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Errors overview. */
                    message: string;
                    /** @description A detailed description of each field that failed validation. */
                    errors: {
                        [key: string]: string[];
                    };
                };
            };
        };
        /** @description Unauthenticated */
        AuthenticationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
        /** @description Authorization error */
        AuthorizationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
        /** @description Not found */
        ModelNotFoundException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "annotation.store": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The session ID */
                session: number;
                type: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    body: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Annotation created.";
                        data: {
                            id: string;
                        };
                        /** @constant */
                        code: 201;
                        error: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "annotation.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The annotation ID */
                annotation: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    body: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Annotation updated.";
                        data: string;
                        /** @constant */
                        code: 200;
                        error: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "annotation.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The annotation ID */
                annotation: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Annotation deleted.";
                        data: string;
                        /** @constant */
                        code: 200;
                        error: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "annotation.reply": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The annotation ID */
                annotation: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    body: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Reply added.";
                        data: {
                            id: number;
                        };
                        /** @constant */
                        code: 201;
                        error: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "auth.login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Login successful.";
                        data: {
                            user: components["schemas"]["UserResource"];
                            token: string;
                        };
                        /** @constant */
                        code: 200;
                        error: boolean;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "auth.register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Registration successful.";
                        data: {
                            user: components["schemas"]["UserResource"];
                            team: components["schemas"]["TeamResource"] | null;
                            /** @constant */
                            team_membership_status: "pending";
                            token: string;
                        };
                        /** @constant */
                        code: 201;
                        error: boolean;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "auth.logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Logout successful.";
                        data: string;
                        /** @constant */
                        code: 200;
                        error: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "dashboard.header": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Dashboard header retrieved.";
                        data: {
                            identity: {
                                team: components["schemas"]["TeamResource"];
                                user: components["schemas"]["UserResource"];
                                analysis_ready_count: number;
                            };
                            window: {
                                sessions_requested: number;
                                sessions_analyzed: number;
                                from: string;
                                to: string;
                            };
                            kpi: {
                                /** @constant */
                                message: "Insufficient sessions queried for KPI of Communication";
                            } | {
                                comm_frequency: number;
                                alignment_rate: number | null;
                                absence_ms: number;
                                calls_classified: number;
                            };
                            comm_mix: {
                                /** @constant */
                                message: "Insufficient sessions queried for Communication Mix";
                            } | {
                                informative: number;
                                declarative: number;
                                compound: number;
                                redundant: number;
                                absence: number;
                                calls_classified: number;
                            };
                        };
                        /** @constant */
                        code: 200;
                        error: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
        };
    };
    "dashboard.players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Dashboard players retrieved.";
                        data: {
                            window: {
                                sessions_requested: number;
                                sessions_analyzed: number;
                                from: string;
                                to: string;
                            };
                            players: string;
                        };
                        /** @constant */
                        code: 200;
                        error: boolean;
                    } | {
                        /** @constant */
                        message: "Dashboard players retrieved.";
                        data: {
                            window: {
                                sessions_requested: number;
                                sessions_analyzed: number;
                                from: string;
                                to: string;
                            };
                            you: {
                                user_id: number;
                                comm_frequency: number;
                                alignment_rate: number | null;
                                calls_logged: number;
                            };
                            team_median: {
                                comm_frequency: number | null;
                                alignment_rate: number | null;
                                calls_logged: number | null;
                            };
                        };
                        /** @constant */
                        code: 200;
                        error: boolean;
                    } | {
                        /** @constant */
                        message: "Dashboard players retrieved.";
                        data: {
                            window: {
                                sessions_requested: number;
                                sessions_analyzed: number;
                                from: string;
                                to: string;
                            };
                            /** @constant */
                            message: "Insufficient sessions queried for Player Stats";
                        };
                        /** @constant */
                        code: 200;
                        error: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
        };
    };
    "session.index": {
        parameters: {
            query?: {
                search?: string;
                sort?: "asc" | "desc";
                per_page?: number;
            };
            header?: never;
            path: {
                /** @description The team ID */
                team: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Sessions retrieved.";
                        data: {
                            live_session: components["schemas"]["SessionResource"] | null;
                            past_sessions: components["schemas"]["SessionResource"][];
                            pagination: {
                                current_page: number;
                                total_pages: number;
                                count: string;
                                per_page: number;
                                total: number;
                            };
                        };
                        /** @constant */
                        code: 200;
                        error: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "session.store": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The team ID */
                team: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreSessionRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Session created.";
                        data: {
                            session: components["schemas"]["SessionResource"] & Record<string, never>;
                        };
                        /** @constant */
                        code: 201;
                        error: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "session.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The session ID */
                session: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Session retrieved.";
                        data: {
                            session: components["schemas"]["SessionResource"] & Record<string, never>;
                        };
                        /** @constant */
                        code: 200;
                        error: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "session.captions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The session ID */
                session: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Session captions retrieved.";
                        data: components["schemas"]["SessionCaptionsResource"];
                        /** @constant */
                        code: 200;
                        error: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "session.timeline": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The session ID */
                session: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Session timeline retrieved.";
                        data: components["schemas"]["SessionTimelineResource"];
                        /** @constant */
                        code: 200;
                        error: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "session.timelineSummary": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The session ID */
                session: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Session timeline summary retrieved.";
                        data: components["schemas"]["SessionTimelineSummaryResource"];
                        /** @constant */
                        code: 200;
                        error: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "session.transition": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The session ID */
                session: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    to: "cancelled" | "reanalyze" | "analysis_ready" | "timeline_ready";
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "session.join": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The session ID */
                session: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Joined session.";
                        data: {
                            session: components["schemas"]["SessionResource"] & Record<string, never>;
                        };
                        /** @constant */
                        code: 200;
                        error: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "session.consent": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The session ID */
                session: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Consent recorded.";
                        data: {
                            session: components["schemas"]["SessionResource"] & Record<string, never>;
                        };
                        /** @constant */
                        code: 200;
                        error: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                        data: string;
                        /** @constant */
                        code: 422;
                        error: boolean;
                    };
                };
            };
        };
    };
    "session.start": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The session ID */
                session: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Session started.";
                        data: {
                            session: components["schemas"]["SessionResource"] & Record<string, never>;
                        };
                        /** @constant */
                        code: 200;
                        error: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                        data: string;
                        /** @constant */
                        code: 422;
                        error: boolean;
                    };
                };
            };
        };
    };
    "session.complete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The session ID */
                session: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["CompleteSessionRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Session completed.";
                        data: {
                            session: components["schemas"]["SessionResource"] & Record<string, never>;
                        };
                        /** @constant */
                        code: 200;
                        error: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "team.join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinTeamRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Join request submitted.";
                        data: {
                            team: components["schemas"]["TeamResource"];
                        };
                        /** @constant */
                        code: 200;
                        error: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "team.show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Team retrieved.";
                        data: {
                            team: components["schemas"]["TeamResource"] & Record<string, never>;
                        };
                        /** @constant */
                        code: 200;
                        error: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
        };
    };
    "team.update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateTeamRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Team updated.";
                        data: {
                            team: components["schemas"]["TeamResource"];
                        };
                        /** @constant */
                        code: 200;
                        error: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "team.removeMember": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The user ID */
                user: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Member removed from the team.";
                        data: string;
                        /** @constant */
                        code: 200;
                        error: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "This member cannot be removed.";
                        data: string;
                        /** @constant */
                        code: 422;
                        error: boolean;
                    };
                };
            };
        };
    };
    "team.leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "You left the team.";
                        data: string;
                        /** @constant */
                        code: 200;
                        error: boolean;
                    } | {
                        /** @constant */
                        message: "You left the team. The team has been disbanded.";
                        data: string;
                        /** @constant */
                        code: 200;
                        error: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "You are not an active member of this team.";
                        data: string;
                        /** @constant */
                        code: 422;
                        error: boolean;
                    };
                };
            };
        };
    };
    "team.joinRequests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Pending join requests retrieved.";
                        data: {
                            requests: components["schemas"]["TeamMemberResource"][];
                        };
                        /** @constant */
                        code: 200;
                        error: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
        };
    };
    "team.decideJoinRequest": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The user ID */
                user: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecideJoinRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Join request approved.";
                        data: {
                            team: components["schemas"]["TeamResource"];
                        };
                        /** @constant */
                        code: 200;
                        error: boolean;
                    } | {
                        /** @constant */
                        message: "Join request rejected.";
                        data: string;
                        /** @constant */
                        code: 200;
                        error: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "teamSettings.show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Team settings retrieved.";
                        data: {
                            settings: components["schemas"]["TeamSettingsResource"];
                        };
                        /** @constant */
                        code: 200;
                        error: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "teamSettings.update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTeamSettingsRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Team settings updated.";
                        data: {
                            settings: components["schemas"]["TeamSettingsResource"];
                        };
                        /** @constant */
                        code: 200;
                        error: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "teamSettings.updateKeywords": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTeamKeywordsRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Team keywords updated.";
                        data: {
                            settings: components["schemas"]["TeamSettingsResource"];
                        };
                        /** @constant */
                        code: 200;
                        error: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "timestamp.store": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The session ID */
                session: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    participant_id: number;
                    /** @enum {string} */
                    communication_type: "informative" | "declarative" | "compound";
                    content: string;
                    start_ms: number;
                    end_ms: number;
                    type?: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Timestamp created.";
                        data: {
                            id: number;
                            type: unknown;
                        };
                        /** @constant */
                        code: 201;
                        error: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "timestamp.reviewAll": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The session ID */
                session: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "All timestamps marked reviewed.";
                        data: {
                            reviewed: string;
                            total: number;
                        };
                        /** @constant */
                        code: 200;
                        error: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "timestamp.review": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The session ID */
                session: number;
                type: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    reviewed: boolean;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Timestamp review set.";
                        data: {
                            reviewed: string;
                            total: number;
                        };
                        /** @constant */
                        code: 200;
                        error: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "timestamp.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The session ID */
                session: number;
                type: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Timestamp updated.";
                        data: string;
                        /** @constant */
                        code: 200;
                        error: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "timestamp.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The session ID */
                session: number;
                type: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Timestamp deleted.";
                        data: string;
                        /** @constant */
                        code: 200;
                        error: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "user.show_2": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Profile retrieved.";
                        data: {
                            user: components["schemas"]["UserResource"] & Record<string, never>;
                        };
                        /** @constant */
                        code: 200;
                        error: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "user.show_4": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Profile retrieved.";
                        data: {
                            user: components["schemas"]["UserResource"] & Record<string, never>;
                        };
                        /** @constant */
                        code: 200;
                        error: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "user.update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Profile updated.";
                        data: {
                            user: components["schemas"]["UserResource"] & Record<string, never>;
                        };
                        /** @constant */
                        code: 200;
                        error: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "user.updatePassword": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePasswordRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Password updated.";
                        data: string;
                        /** @constant */
                        code: 200;
                        error: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "user.teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Active teams retrieved.";
                        data: {
                            teams: components["schemas"]["TeamResource"][];
                        };
                        /** @constant */
                        code: 200;
                        error: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
}
